### ISSUE TITLE
Plugins do not work in 4.1.1

### ISSUE THREAD

**Issue by cy1mat1auto** [paulloz/godot-ink#85]
**Describe the bug**

Newly-created projects cannot use plugins either from Github or AssetLib. Plugins appear in list, but error message displays when trying to enable the plugin (GodotInk as example):

 GodotInk could not be loaded.
  Make sure your .csproj file references GodotInk.props, and rebuild the solution.
  See the installation guide for more information: https://github.com/paulloz/godot-ink/wiki
  If you think this is not an issue on your end, please open a bug report: https://github.com/paulloz/godot-ink/issues/new/choose

**To Reproduce**

Create a new project and download GodotInk from the AssetLib.

Try to enable the plugin.

**Environment**
* OS: 
* Windows
* Godot version: 
* 4.1.1
* godot-ink version: 
* 1.1.1
* ink version: 

**Additional context**

**Comment by paulloz** [comment]
Hello. If the "to reproduce" section of your bug report is accurate to what you are doing, I invite you to consult the installation guide (you linked it above by pasting the activation error). If you did follow the guide, you probably have a compilation error when trying to build your solution.

**Comment by cy1mat1auto** [comment]
Resolved. I forgot to put the extra line in the .csproj after I rebuilt the project.
