### ISSUE TITLE
4.2.2 GDScript Interop issue

### ISSUE THREAD

**Issue by Bard09** [paulloz/godot-ink#90]
**Describe the bug**
After upgrading from 4.2 to 4.2.2 I am seeing several errors in my GDScript code that reference GodotInk C# methods via Interop.  Here are two examples of the error:

>   res://Main.gd:303 - Parse Error: Too few arguments for "EvaluateFunction()" call. Expected at least 2 but received 1.
  res://Main.gd:377 - Parse Error: Too few arguments for "BindExternalFunction()" call. Expected at least 3 but received 2.

GDScript references to C# methods appear to be binding now to the non-Interop C# methods in InkStory in GDScript rather than the Interop ones.

**To Reproduce**
Call C# methods successfully in GDScript via Interop in 4.2; upgrade to Godot 4.2.2, and there should be errors displayed on load of the 4.2 project.

As an example of the EvaluateFunction error above, here's what reproduces it in 4.2.2 with an Ink Story that has a function called "now":

```
var story: InkStory = preload("res://Story.ink")
var date: String = story.EvaluateFunction("now")
```

**Environment**
* OS: Windows 11
* Godot version: 4.2.2 mono
* godot-ink version: 1.1.2

**Additional context**
This is the first time I've upgraded Godot, so if there's an implicit post-upgrade step I've missed, let me know :)

Could this 4.2.2 C# change be indicative that perhaps we may not need the Interop methods any more?  (maybe I'm talking crazy!)

**Comment by paulloz** [comment]
Thank you for the report.

After a bunch of testing, this looks like a regression in Godot itself, and was reported as such[^1].  
In the meantime, you should be able to call the long versions of those methods. E.g., calling `story.EvaluateFunction("now")` is the same thing as calling `story.EvaluateFunction("now", [])`. The second arguments being the array of arguments you'd pass to the ink function (nothing).

Sorry for the inconvenience.

[^1]: godotengine/godot#90946

**Comment by Bard09** [comment]
It looks like [https://github.com/godotengine/godot/pull/90968](url) was fixed in the recent 4.3 release.  I haven't had a chance to upgrade yet but looking forward to see if this resolves this issue!

**Comment by Bard09** [comment]
Ok, it's been a year-- time flies-- but I was able to test this in 4.3.  It does appear that the reported bug is fixed!  (woo!).  However, I am seeing a different warning related to the same sample code in the original bug report.  We might've discussed this scenario before, but I thought I'd mention it anyway.  😄 

To recap, in my GDScript code, I am calling an Ink function on my story titled _"now"_ with godot-ink's _EvaluateFunction_ method.

`var story: InkStory = preload("res://Story.ink")
var date: String = story.EvaluateFunction("now")`

The above code pops this warning:

> The method "EvaluateFunction()" is not present on the inferred type "res://addons/GodotInk/Src/InkStory.cs" (but may be present on a subtype).
>   <GDScript Error>UNSAFE_METHOD_ACCESS
>   <GDScript Source>Main.gd:303

My usual strategy for warnings like this in GDScript is to ensure I'm statically typing everything correctly-- but in this case, I am already doing so, casting story to InkStory upfront.

Is this a warning I should just ignore given how GDScript calling C# works, or is this a new issue post 4.3?
